version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "09:00"
    timezone: America/Chicago
  open-pull-requests-limit: 10
  reviewers:
  - somewhatabstract
  ignore:
  - dependency-name: rollup-plugin-visualizer
    versions:
    - 4.2.1
    - 5.4.0
  - dependency-name: "@babel/core"
    versions:
    - 7.13.13
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.13.8
  - dependency-name: "@babel/plugin-proposal-class-properties"
    versions:
    - 7.12.13
