coverage:
  precision: 2
  round: down
  range: "90...100"

  ignore:
    - "src/index.ts"

  status:
    project:
      default: true
    patch:
      default: false
    changes:
      default: false

comment:
  layout: "header, reach, diff, flags, files, footer"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true