name: Node CI

on:
  pull_request:
    branches:
    - main
    - changeset-release/*

  push:
    branches:
    - main
    - changeset-release/*

jobs:
  lint:
    name: Lint and type check
    env:
      CI: true
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [16.x]
    steps:
    - uses: actions/checkout@v3
    - name: Install & cache node_modules
      uses: Khan/actions@shared-node-cache-v0
      with:
        node-version: ${{ matrix.node-version }}
    - name: Lint
      run: yarn lint
    - name: Types
      run: yarn typecheck
    - name: Changesets check
      uses: Khan/actions@check-for-changeset-v0
      if: |
        github.actor != 'dependabot[bot]' &&
        github.actor != 'dependabot-preview[bot]' &&
        github.event_name == 'pull_request'
      with:
        exclude: .github/,.storybook/

  coverage:
    name: Update test coverage
    env:
      CI: true
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [16.x]
    steps:
    - uses: actions/checkout@v3
    - name: Install & cache node_modules
      uses: Khan/actions@shared-node-cache-v0
      with:
        node-version: ${{ matrix.node-version }}
    - name: Run tests with coverage
      run: yarn coverage
    - name: Upload coverage
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}


  test_and_build:
    needs: [coverage, lint]
    name: Test and build
    env:
      CI: true
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        node-version: [16.x, 18.x]
    steps:
    - uses: actions/checkout@v3
    - name: Install & cache node_modules
      uses: Khan/actions@shared-node-cache-v0
      with:
        node-version: ${{ matrix.node-version }}
    - name: Run tests and build
      run: yarn build
