name: Node CI

on:
  pull_request:
    branches:
    - master

  push:
    branches:
    - master

jobs:
  install:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macOS-latest]
        node-version: [8.x, 10.x, 12.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: yarn install


  lint:
    needs: install
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macOS-latest]
        node-version: [8.x, 10.x, 12.x]
    steps:
    - name: Lint
      run: yarn lint
    - name: Flow
      run: yarn flow:ci


  build:
    needs: install
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macOS-latest]
        node-version: [8.x, 10.x, 12.x]
    steps:
      - name: Build dist
        run: yarn build
        env:
          CI: true


  coverage:
    needs: install
    runs-on: ubuntu-latest
    node-version: 12.x
    steps:
    - name: Run tests with coverage
      run: yarn coverage
      env:
        CI: true
    - name: Upload coverage
      run: yarn codecov
      env:
        CI: true
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

